### ISSUE TITLE
Does not work with upper case drive letters

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/uncmap#8]
If I copy a link from the file Explorer, it is always upper case drive letter. Within the wiki uncmap-links with upper case drive letters are not supported by the plugin until now. If I change the drive letter to lower case, it works fine. (the conf/mapping.php defines that it has to be lower case, but I hoped only within this config file...)

**Comment by micgro42** [comment]
Actually it should be enough to be consistent between conf/mapping.php and the link given on the page.
However I've added a quick fix, which still needs testing.

If you want, you can check out that branch on my fork: https://github.com/micgro42/uncmap/tree/fixUppercase

**Comment by splitbrain** [comment]
looked good to me. merged
